## Refer to http://caffe.berkeleyvision.org/installation.html
# Contributions simplifying and improving our build system are welcome!

# CUDA directory contains bin/ and lib/ directories that we need.
CUDA_DIR := /usr/local/cuda
#CUDA_DIR  := /usr/local/cuda-5.5

# CUDA architecture setting: going with all of them (up to CUDA 5.5 compatible).
# For the latest architecture, you need to install CUDA >= 6.0 and uncomment
# the *_50 lines below.
CUDA_ARCH := -gencode arch=compute_20,code=sm_20 \
		-gencode arch=compute_30,code=sm_30 \
		-gencode arch=compute_35,code=sm_35
		#-gencode arch=compute_20,code=sm_21 \
		#-gencode=arch=compute_50,code=sm_50 \
		#-gencode=arch=compute_50,code=compute_50

# BLAS choice:
# atlas for ATLAS (default)
# mkl for MKL
# open for OpenBlas
BLAS := atlas
# Custom (MKL/ATLAS/OpenBLAS) include and lib directories.
# Leave commented to accept the defaults for your choice of BLAS
# (which should work)!
# BLAS_INCLUDE := /path/to/your/blas
# BLAS_LIB := /path/to/your/blas

# This is required only if you will compile the matlab interface.
# MATLAB directory should contain the mex binary in /bin.
#MATLAB_DIR := /usr/local/MATLAB/R2012a
MATLAB_DIR := /usr/local/matlab
# MATLAB_DIR := /pkgs/matlab-80
# MATLAB_DIR := /usr/local
# MATLAB_DIR := /Applications/MATLAB_R2012b.app

# NOTE: this is required only if you will compile the python interface.
# We need to be able to find Python.h and numpy/arrayobject.h.
PYTHON_INCLUDE := /usr/include/python2.7 \
		/usr/lib/python2.7/dist-packages/numpy/core/include
# Anaconda Python distribution is quite popular. Include path:
# PYTHON_INCLUDE := $(HOME)/anaconda/include \
		# $(HOME)/anaconda/include/python2.7 \
		# $(HOME)/anaconda/lib/python2.7/site-packages/numpy/core/include

# We need to be able to find libpythonX.X.so or .dylib.
PYTHON_LIB := /usr/lib
# PYTHON_LIB := $(HOME)/anaconda/lib

# Whatever else you find you need goes here. 
#Jay add: PYTHON_LIB will screw up the linker because it links to older protobuf
#INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include $(HOME)/local/include
LIBRARY_DIRS := $(HOME)/local/lib /usr/local/lib /usr/lib # $(HOME)/workspace/ext/hdf5-1.8.13/lib
INCLUDE_DIRS := $(PYTHON_INCLUDE) $(HOME)/local/include /usr/local/include # $(HOME)/workspace/ext/hdf5-1.8.13/include
#LIBRARY_DIRS := $(PYTHON_LIB) $(HOME)/local/lib /usr/local/lib /usr/lib /usr/lib/x86_64-linux-gnu/

BUILD_DIR := build
DISTRIBUTE_DIR := distribute

# Uncomment for debugging.
DEBUG := 1

# The ID of the GPU that 'make runtest' will use to run unit tests.
TEST_GPUID := 0
